In [1]:
import polars as pl
import numpy as np
import scipy

print("polars:", pl.__version__)
print("numpy:", np.__version__)
print("scipy:", scipy.__version__)

polars: 1.38.1
numpy: 2.4.3
scipy: 1.17.1

In [2]:
import sys
print(sys.path)

['C:\\Users\\mattm\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\mattm\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\mattm\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\mattm\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\mattm\\documents\\kingshot-ttg\\.venv', '', 'C:\\Users\\mattm\\documents\\kingshot-ttg\\.venv\\Lib\\site-packages']

In [1]:
from ttg.newcostlookup import tc_requirements_for_target
tc_requirements_for_target(7)

{'Embassy': 6, 'Barracks': 5, 'Range': 6, 'Stable': 4}

In [3]:
from ttg.cost_lookup import lookup_targets
lookup_targets(5, 7, "TC_RBS_CC")

LookupTotals(truegold=5274, tempered_truegold=379)

In [3]:
print(ttg)

<module 'ttg' from 'C:\\Users\\mattm\\Documents\\kingshot-ttg\\src\\ttg\\__init__.py'>

In [1]:
from ttg import cost_model

In [2]:
cost_model.cost_one_week(100)

8710.0

In [4]:
from ttg.cost_lookup import (
    lookup_target_tg,
    lookup_target_ttg,
    lookup_targets,
    lookup_building_targets,
    custom_scenario_cost,
)

print(lookup_target_ttg(6, "Troops"))          # alias -> TC_RBS
print(lookup_target_ttg(7, "Troops+CC"))       # alias -> TC_RBS_CC
print(lookup_target_ttg(8, "All Buildings"))   # alias -> ALL_TG

print(lookup_targets(7, "TC_RBS"))
print(lookup_building_targets(6, "TC_RBS_CC"))

custom = {
    "Town Center": (5, 8),
    "Embassy": (5, 7),
    "Command Center": (5, 6),
    "Infirmary": (5, 5),
    "Barracks": (5, 8),
    "Range": (5, 8),
    "Stable": (5, 8),
    "War Academy": (5, 5),
}
print(custom_scenario_cost(custom))

135
379
907
CostTotals(truegold=4878, tempered_truegold=349)
{'Town Center': 6, 'Embassy': 5, 'Command Center': 6, 'Infirmary': 5, 'Barracks': 6, 'Range': 6, 'Stable': 6, 'War Academy': 5}
CostTotals(truegold=7866, tempered_truegold=665)

In [5]:
from ttg.probabilities import validate_probability_table
from ttg.cost_lookup import lookup_target_ttg, lookup_targets
from ttg.planner import (
    probability_for_even_distribution,
    probability_for_plan,
    optimal_plan_from_lookup,
    plan_to_dict,
    plan_table_rows,
)

print(validate_probability_table())
print(lookup_target_ttg(6, "Troops"))
print(lookup_targets(7, "All Buildings"))

print(probability_for_even_distribution(300, 200, 2))
print(probability_for_plan(100, [42, 27]))
print(probability_for_plan(100, [35, 35]))

result = optimal_plan_from_lookup(6, "Troops", 2, 0.95)
print(plan_to_dict(result))

rows = plan_table_rows(
    tg_level=6,
    scenario="Troops",
    weeks=2,
    probabilities=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99, 1.0],
)
rows[:2]

shape: (5, 5)
┌──────┬──────────┬───────────┬───────────┬────────────┐
│ tier ┆ prob_sum ┆ min_yield ┆ max_yield ┆ n_outcomes │
│ ---  ┆ ---      ┆ ---       ┆ ---       ┆ ---        │
│ i64  ┆ f64      ┆ i64       ┆ i64       ┆ u32        │
╞══════╪══════════╪═══════════╪═══════════╪════════════╡
│ 1    ┆ 1.0      ┆ 1         ┆ 3         ┆ 3          │
│ 2    ┆ 1.0      ┆ 2         ┆ 3         ┆ 2          │
│ 3    ┆ 1.0      ┆ 3         ┆ 6         ┆ 4          │
│ 4    ┆ 1.0      ┆ 3         ┆ 9         ┆ 7          │
│ 5    ┆ 1.0      ┆ 3         ┆ 12        ┆ 10         │
└──────┴──────────┴───────────┴───────────┴────────────┘
135
CostTotals(truegold=6831, tempered_truegold=490)
1.0
1.0
0.9999999999999989
{'target_ttg': 135, 'current_ttg': 0, 'used_this_week': 0, 'weeks': 2, 'requested_probability': 0.95, 'achieved_probability': 0.9618334801683032, 'total_refines': 77, 'total_cost': 2455.0, 'week_refines': [45, 32]}

[{'tg_level': 6,
  'scenario': 'Troops',
  'requested_probability': 0.25,
  'target_ttg': 135,
  'current_ttg': 0,
  'used_this_week': 0,
  'total_refines': 72,
  'total_cost': 2205.0,
  'achieved_probability': 0.2885227456046136,
  'week_1': 45,
  'week_2': 27},
 {'tg_level': 6,
  'scenario': 'Troops',
  'requested_probability': 0.5,
  'target_ttg': 135,
  'current_ttg': 0,
  'used_this_week': 0,
  'total_refines': 73,
  'total_cost': 2280.0,
  'achieved_probability': 0.5413853841983308,
  'week_1': 46,
  'week_2': 27}]

In [1]:
from ttg.tables import build_plan_table
from ttg.planner import evaluate_plan, evaluate_plan_from_lookup

In [2]:
%%time
df = build_plan_table(
    tg_level=7,
    scenario="All",
    weeks=2,
    # probabilities=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 1.00],
)

df

CPU times: total: 125 ms
Wall time: 152 ms

shape: (7, 12)
┌──────────┬──────────┬────────────────────┬────────────┬───┬────────┬───────────────┬────────────┬────────────────────┐
│ tg_level ┆ scenario ┆ requested_probabil ┆ target_ttg ┆ … ┆ week_2 ┆ total_refines ┆ total_cost ┆ achieved_probabili │
│ ---      ┆ ---      ┆ ity                ┆ ---        ┆   ┆ ---    ┆ ---           ┆ ---        ┆ ty                 │
│ i64      ┆ str      ┆ ---                ┆ i64        ┆   ┆ i64    ┆ i64           ┆ f64        ┆ ---                │
│          ┆          ┆ f64                ┆            ┆   ┆        ┆               ┆            ┆ f64                │
╞══════════╪══════════╪════════════════════╪════════════╪═══╪════════╪═══════════════╪════════════╪════════════════════╡
│ 7        ┆ All      ┆ 0.25               ┆ 490        ┆ … ┆ 84     ┆ 180           ┆ 14380.0    ┆ 0.2533             │
│ 7        ┆ All      ┆ 0.5                ┆ 490        ┆ … ┆ 84     ┆ 182           ┆ 14700.0    ┆ 0.508823           │
│ 7        ┆ All      ┆ 0.75               ┆ 490        ┆ … ┆ 84     ┆ 184           ┆ 15020.0    ┆ 0.766177           │
│ 7        ┆ All      ┆ 0.9                ┆ 490        ┆ … ┆ 86     ┆ 186           ┆ 15340.0    ┆ 0.926974           │
│ 7        ┆ All      ┆ 0.95               ┆ 490        ┆ … ┆ 87     ┆ 187           ┆ 15500.0    ┆ 0.966203           │
│ 7        ┆ All      ┆ 0.99               ┆ 490        ┆ … ┆ 89     ┆ 189           ┆ 15820.0    ┆ 0.995348           │
│ 7        ┆ All      ┆ 1.0                ┆ 490        ┆ … ┆ 98     ┆ 198           ┆ 17260.0    ┆ 1.0                │
└──────────┴──────────┴────────────────────┴────────────┴───┴────────┴───────────────┴────────────┴────────────────────┘

In [3]:
%%time
df8 = build_plan_table(
    tg_level=7,
    scenario="All Buildings",
    weeks=8,
    # probabilities=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 1.00],
)

df8

CPU times: total: 2.94 s
Wall time: 3.23 s

shape: (7, 18)
┌──────────┬───────────────┬──────────────────┬────────────┬───┬────────┬───────────────┬────────────┬─────────────────┐
│ tg_level ┆ scenario      ┆ requested_probab ┆ target_ttg ┆ … ┆ week_8 ┆ total_refines ┆ total_cost ┆ achieved_probab │
│ ---      ┆ ---           ┆ ility            ┆ ---        ┆   ┆ ---    ┆ ---           ┆ ---        ┆ ility           │
│ i64      ┆ str           ┆ ---              ┆ i64        ┆   ┆ i64    ┆ i64           ┆ f64        ┆ ---             │
│          ┆               ┆ f64              ┆            ┆   ┆        ┆               ┆            ┆ f64             │
╞══════════╪═══════════════╪══════════════════╪════════════╪═══╪════════╪═══════════════╪════════════╪═════════════════╡
│ 7        ┆ All Buildings ┆ 0.25             ┆ 490        ┆ … ┆ 24     ┆ 277           ┆ 7820.0     ┆ 0.258607        │
│ 7        ┆ All Buildings ┆ 0.5              ┆ 490        ┆ … ┆ 24     ┆ 280           ┆ 7970.0     ┆ 0.515846        │
│ 7        ┆ All Buildings ┆ 0.75             ┆ 490        ┆ … ┆ 24     ┆ 283           ┆ 8120.0     ┆ 0.769576        │
│ 7        ┆ All Buildings ┆ 0.9              ┆ 490        ┆ … ┆ 24     ┆ 286           ┆ 8270.0     ┆ 0.926025        │
│ 7        ┆ All Buildings ┆ 0.95             ┆ 490        ┆ … ┆ 24     ┆ 287           ┆ 8320.0     ┆ 0.954112        │
│ 7        ┆ All Buildings ┆ 0.99             ┆ 490        ┆ … ┆ 24     ┆ 290           ┆ 8470.0     ┆ 0.992097        │
│ 7        ┆ All Buildings ┆ 1.0              ┆ 490        ┆ … ┆ 26     ┆ 306           ┆ 9270.0     ┆ 1.0             │
└──────────┴───────────────┴──────────────────┴────────────┴───┴────────┴───────────────┴────────────┴─────────────────┘

In [4]:
%%time

df8 = build_plan_table(
    tg_level=7,
    scenario="All Buildings",
    weeks=8,
    probabilities=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 1.00],
    prob_bucket=0.001,
    max_frontier_states=4000,
)

df8

CPU times: total: 2.48 s
Wall time: 2.63 s

shape: (7, 17)
┌──────────┬───────────────┬──────────────────┬────────────┬───┬────────┬───────────────┬────────────┬─────────────────┐
│ tg_level ┆ scenario      ┆ requested_probab ┆ target_ttg ┆ … ┆ week_8 ┆ total_refines ┆ total_cost ┆ achieved_probab │
│ ---      ┆ ---           ┆ ility            ┆ ---        ┆   ┆ ---    ┆ ---           ┆ ---        ┆ ility           │
│ i64      ┆ str           ┆ ---              ┆ i64        ┆   ┆ i64    ┆ i64           ┆ f64        ┆ ---             │
│          ┆               ┆ f64              ┆            ┆   ┆        ┆               ┆            ┆ f64             │
╞══════════╪═══════════════╪══════════════════╪════════════╪═══╪════════╪═══════════════╪════════════╪═════════════════╡
│ 7        ┆ All Buildings ┆ 0.25             ┆ 490        ┆ … ┆ 26     ┆ 277           ┆ 7770.0     ┆ 0.258607        │
│ 7        ┆ All Buildings ┆ 0.5              ┆ 490        ┆ … ┆ 26     ┆ 280           ┆ 7920.0     ┆ 0.515846        │
│ 7        ┆ All Buildings ┆ 0.75             ┆ 490        ┆ … ┆ 26     ┆ 283           ┆ 8070.0     ┆ 0.769576        │
│ 7        ┆ All Buildings ┆ 0.9              ┆ 490        ┆ … ┆ 26     ┆ 286           ┆ 8220.0     ┆ 0.926025        │
│ 7        ┆ All Buildings ┆ 0.95             ┆ 490        ┆ … ┆ 26     ┆ 287           ┆ 8270.0     ┆ 0.954112        │
│ 7        ┆ All Buildings ┆ 0.99             ┆ 490        ┆ … ┆ 26     ┆ 290           ┆ 8420.0     ┆ 0.992097        │
│ 7        ┆ All Buildings ┆ 1.0              ┆ 490        ┆ … ┆ 26     ┆ 306           ┆ 9220.0     ┆ 1.0             │
└──────────┴───────────────┴──────────────────┴────────────┴───┴────────┴───────────────┴────────────┴─────────────────┘

In [1]:
import polars as pl
from ttg.planner import inspect_candidate_family
from ttg.cost_lookup import lookup_target_ttg

import polars as pl

pl.Config.set_tbl_rows(-1)
pl.Config.set_tbl_cols(-1)
pl.Config.set_fmt_str_lengths(200)
pl.Config.set_fmt_table_cell_list_len(50)

target = lookup_target_ttg(7, "All Buildings")
pl.DataFrame(inspect_candidate_family(target, total_refines=304, weeks=8))

shape: (25, 8)
┌────────────┬─────────────┬────────────────┬───────┬──────────────────┬───────────────┬────────────┬──────────────────┐
│ target_ttg ┆ current_ttg ┆ used_this_week ┆ weeks ┆ week_refines     ┆ total_refines ┆ total_cost ┆ achieved_probabi │
│ ---        ┆ ---         ┆ ---            ┆ ---   ┆ ---              ┆ ---           ┆ ---        ┆ lity             │
│ i64        ┆ i64         ┆ i64            ┆ i64   ┆ list[i64]        ┆ i64           ┆ f64        ┆ ---              │
│            ┆             ┆                ┆       ┆                  ┆               ┆            ┆ f64              │
╞════════════╪═════════════╪════════════════╪═══════╪══════════════════╪═══════════════╪════════════╪══════════════════╡
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [38, 38, 38, 38, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 38, 38, 38, 38]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [39, 38, 38, 38, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 38, 38, 38, 37]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [39, 39, 38, 38, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 38, 38, 37, 37]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [39, 39, 39, 38, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 38, 37, 37, 37]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [39, 39, 39, 39, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 37, 37, 37, 37]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [40, 38, 38, 38, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 38, 38, 37, 37]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [40, 38, 38, 38, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 38, 38, 38, 36]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [40, 39, 38, 38, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 38, 37, 37, 37]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [40, 39, 38, 38, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 38, 38, 38, 35]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [40, 39, 39, 38, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 37, 37, 37, 37]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [40, 40, 39, 39, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 38, 38, 38, 32]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [40, 40, 40, 39, ┆ 304           ┆ 9120.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 39, 39, 38, 29]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [43, 38, 38, 37, ┆ 304           ┆ 9195.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 37, 37, 37, 37]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [43, 38, 38, 38, ┆ 304           ┆ 9195.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 37, 37, 37, 36]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [43, 38, 38, 38, ┆ 304           ┆ 9195.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 38, 37, 36, 36]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [43, 38, 38, 38, ┆ 304           ┆ 9195.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 38, 38, 38, 33]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [43, 39, 37, 37, ┆ 304           ┆ 9195.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 37, 37, 37, 37]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [48, 37, 37, 37, ┆ 304           ┆ 9370.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 37, 36, 36, 36]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [48, 37, 37, 37, ┆ 304           ┆ 9370.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 37, 37, 36, 35]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [48, 38, 37, 37, ┆ 304           ┆ 9370.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 36, 36, 36, 36]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [48, 38, 38, 36, ┆ 304           ┆ 9370.0     ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 36, 36, 36, 36]  ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [100, 30, 29,    ┆ 304           ┆ 13590.0    ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 29, 29, 29, 29,  ┆               ┆            ┆                  │
│            ┆             ┆                ┆       ┆ 29]              ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [100, 30, 30,    ┆ 304           ┆ 13590.0    ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 29, 29, 29, 29,  ┆               ┆            ┆                  │
│            ┆             ┆                ┆       ┆ 28]              ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [100, 30, 30,    ┆ 304           ┆ 13590.0    ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 30, 29, 29, 28,  ┆               ┆            ┆                  │
│            ┆             ┆                ┆       ┆ 28]              ┆               ┆            ┆                  │
│ 490        ┆ 0           ┆ 0              ┆ 8     ┆ [100, 30, 30,    ┆ 304           ┆ 13590.0    ┆ 1.0              │
│            ┆             ┆                ┆       ┆ 30, 30, 28, 28,  ┆               ┆            ┆                  │
│            ┆             ┆                ┆       ┆ 28]              ┆               ┆            ┆                  │
└────────────┴─────────────┴────────────────┴───────┴──────────────────┴───────────────┴────────────┴──────────────────┘

In [5]:
evaluate_plan(490, 8*[int(300/8)+1])

{'target_ttg': 490,
 'current_ttg': 0,
 'used_this_week': 0,
 'weeks': 8,
 'week_refines': [38, 38, 38, 38, 38, 38, 38, 38],
 'total_refines': 304,
 'total_cost': 9120.0,
 'achieved_probability': 0.9999999993043057}

In [6]:
215/8

26.875

In [6]:
from ttg.planner import compare_plan_set
from ttg.cost_lookup import lookup_target_ttg
import polars as pl

In [7]:
target = lookup_target_ttg(7, "All Buildings")

rows = compare_plan_set(
    target_ttg=target,
    custom_plan=[38,38,38,38,38,38,38,38],
    desired_probability=0.99
)

pl.DataFrame(rows)

shape: (4, 9)
┌──────────────┬────────────┬─────────────┬─────────────┬───────┬─────────────┬─────────────┬────────────┬─────────────┐
│ plan_type    ┆ target_ttg ┆ current_ttg ┆ used_this_w ┆ weeks ┆ week_refine ┆ total_refin ┆ total_cost ┆ achieved_pr │
│ ---          ┆ ---        ┆ ---         ┆ eek         ┆ ---   ┆ s           ┆ es          ┆ ---        ┆ obability   │
│ str          ┆ i64        ┆ i64         ┆ ---         ┆ i64   ┆ ---         ┆ ---         ┆ f64        ┆ ---         │
│              ┆            ┆             ┆ i64         ┆       ┆ list[i64]   ┆ i64         ┆            ┆ f64         │
╞══════════════╪════════════╪═════════════╪═════════════╪═══════╪═════════════╪═════════════╪════════════╪═════════════╡
│ custom       ┆ 490        ┆ 0           ┆ 0           ┆ 8     ┆ [38, 38,    ┆ 304         ┆ 9120.0     ┆ 1.0         │
│              ┆            ┆             ┆             ┆       ┆ 38, 38, 38, ┆             ┆            ┆             │
│              ┆            ┆             ┆             ┆       ┆ 38, 38, 38] ┆             ┆            ┆             │
│ even_split_s ┆ 490        ┆ 0           ┆ 0           ┆ 8     ┆ [38, 38,    ┆ 304         ┆ 9120.0     ┆ 1.0         │
│ ame_total    ┆            ┆             ┆             ┆       ┆ 38, 38, 38, ┆             ┆            ┆             │
│              ┆            ┆             ┆             ┆       ┆ 38, 38, 38] ┆             ┆            ┆             │
│ all_in       ┆ 490        ┆ 0           ┆ 0           ┆ 8     ┆ [100, 100,  ┆ 800         ┆ 69680.0    ┆ 1.0         │
│              ┆            ┆             ┆             ┆       ┆ 100, 100,   ┆             ┆            ┆             │
│              ┆            ┆             ┆             ┆       ┆ 100, 100,   ┆             ┆            ┆             │
│              ┆            ┆             ┆             ┆       ┆ 100, 100]   ┆             ┆            ┆             │
│ optimizer    ┆ 490        ┆ 0           ┆ 0           ┆ 8     ┆ [40, 40,    ┆ 290         ┆ 8420.0     ┆ 0.992097    │
│              ┆            ┆             ┆             ┆       ┆ 40, 40, 40, ┆             ┆            ┆             │
│              ┆            ┆             ┆             ┆       ┆ 38, 26, 26] ┆             ┆            ┆             │
└──────────────┴────────────┴─────────────┴─────────────┴───────┴─────────────┴─────────────┴────────────┴─────────────┘

In [1]:
from ttg.planner import benchmark_plan_solve
from ttg.cost_lookup import lookup_target_ttg

benchmark_plan_solve(
    target_ttg=lookup_target_ttg(7, "All Buildings"),
    weeks=8,
    desired_probability=0.99,
)

{'target_ttg': 490,
 'weeks': 8,
 'desired_probability': 0.99,
 'current_ttg': 0,
 'used_this_week': 0,
 'repeats': 1,
 'seconds_total': 0.3951427999418229,
 'seconds_per_run': 0.3951427999418229,
 'result_plan': [42, 40, 40, 40, 40, 35, 26, 26],
 'result_cost': 8420.0,
 'result_probability': 0.9918598917235253}

In [9]:
from ttg.planner import ttg_max_one_week,ttg_min_one_week, ttg_expected_one_week
n=60
print(
    f'{n} refinements per week:\n\nMin TTG: {ttg_min_one_week(n)}\nExpected TTG: {ttg_expected_one_week(n)}\nMax TTG: {ttg_max_one_week(n)}'
)

60 refinements per week:

Min TTG: 120
Expected TTG: 135.6000000000001
Max TTG: 240

In [11]:
from ttg.planner import optimal_plan
optimal_plan(287,2)

PlanResult(target_ttg=287, current_ttg=0, used_this_week=0, weeks=2, requested_probability=None, achieved_probability=0.999999999938499, total_refines=134, total_cost=7950.0, week_refines=(70, 64))